replicaCount: 1

rbac:
  create: true
  serviceAccount:
    create: true
    # allow HMS connects to AWS resources via IRSA, such as S3 and KMS.
#    annotations: {EMRExecRole}

image:
  name: ghcr.io/melodyyangaws/hive-metastore
  tag: 3.0.0
  pullPolicy: IfNotPresent
env:
  HIVE_DB_EXTERNAL: "true"
  HIVE_DB_DRIVER: com.mysql.cj.jdbc.Driver
  HIVE_CONF_PARAMS: "hive.metastore.schema.verification:false;datanucleus.autoCreateSchema:false"
  HIVE_DB_JDBC_URL: {RDS_JDBC_URL}
  # either hardcoded here or get from Secrets Manager below
  HIVE_DB_USER: {RDS_USERNAME}
  HIVE_DB_PASS: {RDS_PASSWORD}
  HIVE_WAREHOUSE_S3LOCATION: {S3BUCKET}
  HIVE_WAREHOUSE_DIR: {S3BUCKET}

# optional: get sensative info from external secret store, such as AWS Secrets Manager
#secretName: <EKS_SECRET_RESOURCE_NAME>
#secret:
#   HIVE_DB_USER: username
#   HIVE_DB_PASS: password

service:
  type: ClusterIP

resources:
  limits:
    cpu: 1
    memory: 1000Mi
  requests:
    cpu: 400m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

initjob:
  annotation: {}
#    argocd.argoproj.io/hook: Sync
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
