apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-boot-microservice.fullname" . }}
  labels:
    {{- include "spring-boot-microservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spring-boot-microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spring-boot-microservice.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spring-boot-microservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- if (contains "sha256:" .Values.image.tag) }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.tag | trimPrefix "@" | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- end }}

          args:
          {{- with .Values.extraArgs }}
            {{- toYaml . $ | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.service.httpTargetPort }}
              protocol: TCP
            - name: http-management
              containerPort: {{ .Values.service.managementTargetPort }}
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{.Values.service.managementPort}}
            failureThreshold: 3
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.managementPort }}
            failureThreshold: 10
            periodSeconds: 15

          resources:
          {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: LOG4J_CONFIGURATION_FILE
              value: /etc/config/logging.yaml
            - name: JAVA_TOOL_OPTIONS
              value: {{- toYaml .Values.jvmOptions }}
          {{- with .Values.extraEnv }}
              {{- toYaml . $ | nindent 12 }}
          {{- end }}

          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . $ | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: logging
              mountPath: /etc/config/
              readOnly: true
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . $ | nindent 12 }}
          {{- end }}

      volumes:
        - name: logging
          configMap:
            name: {{ include "spring-boot-microservice.fullname" . }}
            items:
              - key: "log4j2.yaml"
                path: logging.yaml
      {{- with .Values.extraVolumes }}
        {{- toYaml . $ | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . $ | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . $ | nindent 8 }}
      {{- end }}
