apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-hs.name" . }}-conf
  labels:
    {{- include "spark-hs.labels" $ | trim | nindent 4 }}
data:
  {{- with .Values.spark.properties }}
  spark-defaults.conf: |
    {{- tpl . $ | nindent 6 }}
  {{- end }}
  {{- with .Values.logger.properties }}
  log4j.properties:
    {{- tpl . $ | nindent 6 }}
  {{- end }}
