apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark-hs.name" . }}
  labels:
    {{- include "spark-hs.labels" $ | trim | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "spark-hs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spark-hs.labels" $ | trim | nindent 8 }}
        {{- include "spark-hs.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spark-hs.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{.Values.image.name}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          command: ["/opt/spark/sbin/start-history-server.sh"]

          env:
            - name: SPARK_CONF_DIR
              value: /opt/spark/conf
          {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: 18080
              protocol: TCP

          readinessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http

          livenessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http

          volumeMounts:
            - name: {{ template "spark-hs.name" . }}-conf
              mountPath: /opt/spark/conf
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.cache.pvc.enabled }}
            - name: cache
              mountPath: /data/cache
            {{- end }}
      volumes:
        - name: {{ template "spark-hs.name" . }}-conf
          configMap:
            name: {{ template "spark-hs.name" . }}-conf
            items:
              - key: spark-defaults.conf
                path: spark-defaults.conf
              - key: log4j.properties
                path: log4j.properties
        {{- if .Values.cache.pvc.enabled }}
        - name: cache
          persistentVolumeClaim:
            claimName: spark-hs-cache
        {{- end }}

        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}



