apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-hs.name" . }}
  labels:
    {{- include "spark-hs.labels" $ | trim | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: history-server
      port: 18080
  selector:
    {{- include "spark-hs.selectorLabels" . | nindent 4 }}
