apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-microservice.fullname" . }}
  labels:
  {{- include "spring-boot-microservice.labels" . | nindent 6 }}
data:
  {{- with .Values.log4j2Config }}
  log4j2.yaml: >-
    {{- tpl . $ | nindent 6 }}
    {{- end }}
